#
# Thanks to https://github.com/google/googletest/ for helping me avoid a lot of problems creating this file.
#
language: cpp

# Still dreaming of a Windows option.
os:
    - linux
    - osx

dist: trusty
sudo: required

# Test both compilers.
compiler:
    - clang
    - gcc

# Ensure the environment is prepared correctly.
before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./TravisCI/LinuxDependencies.sh; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./TravisCI/MacDependencies.sh; fi

# Create the CMake project.
before_script:
    - mkdir Project
    - cd Project
    - cmake .. -DENABLE_TESTING:BOOL=ON

# Finally execute the build.
script:
    - make
    - make test
