#
# Thanks to https://github.com/google/googletest/ for helping me avoid a lot of problems creating this file.
#
language: cpp

matrix:
    include:

        # Ubuntu 14.04 GCC.
        - os: linux
          dist: trusty
          addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-5
          env: COMPILER=g++-5

        # Ubuntu 14.04 GCC.
        - os: linux
          dist: trusty
          addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-5
        env: COMPILER=g++-5







# Still dreaming of a Windows option
os:
    - linux
    - osx

dist: trusty

# Test both compilers
compiler:
    - gcc
    - clang

# Enable a valid compiler version.
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.8"; fi

before_script:

    - mkdir Project
    - cd Project
    - cmake .. -DENABLE_TESTING:BOOL=ON

script: scons
